/*
1 - Criar o banco de dados chamado
SENAI_HROADS_MANHA/SENAI_HROADS_TARDE (conforme o período);
*/
CREATE DATABASE HROADS;
GO

USE HROADS;
GO

/*
2 - Criar as tabelas no banco de dados
*/
CREATE TABLE CLASSE(
	idClasse TINYINT PRIMARY KEY IDENTITY,
	nomeClasse VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE TIPOHABILIDADE(
	idTipoHabilidade TINYINT PRIMARY KEY IDENTITY,
	nomeTipoHabilidade VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE HABILIDADE(
	idHabilidade TINYINT PRIMARY KEY IDENTITY,
	idTipoHabilidade TINYINT FOREIGN KEY REFERENCES TIPOHABILIDADE(idTipoHabilidade),
	nomeHabilidade VARCHAR(40) NOT NULL
);
GO

CREATE TABLE PERSONAGEM(
	idPersonagem SMALLINT PRIMARY KEY IDENTITY,
	idClasse TINYINT FOREIGN KEY REFERENCES CLASSE(idClasse),
	nomePersonagem VARCHAR(50) NOT NULL,
	capacidadeMaxVida TINYINT,
	capacidadeMaxMana TINYINT,
	dataAtualizacao SMALLDATETIME,
	dataCriacao SMALLDATETIME NOT NULL
);
GO

CREATE TABLE CLASSEHABILIDADE(
	idClasseHabilidade SMALLINT PRIMARY KEY IDENTITY,
	idClasse TINYINT FOREIGN KEY REFERENCES CLASSE (idClasse),
	idHabilidade TINYINT FOREIGN KEY REFERENCES HABILIDADE (idHabilidade)
);
GO

CREATE TABLE TIPOUSUARIO (
	idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	titulo VARCHAR(150) NOT NULL UNIQUE
);
GO

CREATE TABLE USUARIO (
	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	email VARCHAR(256) NOT NULL UNIQUE,
	senha VARCHAR(25) NOT NULL
);
